language: node_js
node_js:
  - 10
script:
  - cd website; yarn install; yarn build
  - npx serve build/near-docs & sleep 5; pwd; curl -v http://localhost:5000/; npx broken-link-checker http://localhost:5000/
