language: node_js
node_js:
  - 10
script:
  - cd website; yarn install; yarn build
  - npx serve build/near-docs &
  - npx wait-on http://localhost:5000/
  - npx broken-link-checker -gro --exclude "localhost:3030" --exclude "https://github.com/nearprotocol/docs/tree/master/docs" --host-requests 2 http://localhost:5000