language: node_js
node_js:
  - 10
script:
  - cd website; yarn install; yarn build
  - npx serve website/build/near-docs &
  - curl -v http://localhost:5000/
  - npx broken-link-checker http://localhost:5000/
